In [125]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rd
import pandas as pd

In [131]:
n_points = 8
lst = []

for i in range(n_points):
    lst += [[rd.random(), rd.random()]]

print(lst)

[[0.05117332966962418, 0.05427538497317885], [0.19416258121844154, 0.8782699093283957], [0.04369017937608599, 0.5917911791614647], [0.4970861446272705, 0.8482736076692207], [0.014236252897285473, 0.5214315232080392], [0.1388244044397483, 0.7251550009058794], [0.758455841895224, 0.6730526987448379], [0.9128479558226997, 0.4419072857296067]]


In [132]:
lst = []
for i in range(n_points):
    lst.append([rd.random(), rd.random()])

print(lst)

[[0.04093084097957678, 0.444030406144724], [0.23796016808981846, 0.8402973992652002], [0.721775707609925, 0.2597470664134406], [0.23825881489342426, 0.1988965985881681], [0.1919556481594482, 0.3416677341600436], [0.07330387990634357, 0.35511546377616554], [0.283795576302289, 0.9327366846344055], [0.5665248959780605, 0.20292877204669812]]


In [133]:
lst = [[rd.random(), rd.random()] for _ in range(n_points)]
print(lst)

[[0.563468905503238, 0.6989664898150101], [0.27707904247539294, 0.8333304511102548], [0.7652642247962835, 0.1056599864308495], [0.21473986653880384, 0.1877782922510881], [0.47476146990607315, 0.5051435218549314], [0.7698325879461081, 0.122853930493938], [0.7110277438978478, 0.1578708182641706], [0.3201492605573649, 0.1771052441725105]]


In [146]:
rd.rand(n_points, 2)

array([[0.65357686, 0.29585372],
       [0.35892651, 0.60804507],
       [0.32294058, 0.51923661],
       [0.69014017, 0.03535412],
       [0.21901103, 0.92490107],
       [0.14745622, 0.18265965],
       [0.69319837, 0.74351403],
       [0.29050995, 0.61160838]])

In [144]:
n_points = 8
tab_points = np.zeros([n_points, 2])
for i in range(n_points):
    tab_points[i] = rd.rand(2)

In [152]:
lst1 = [1, 2]
lst2 = [3, 4]

In [153]:
lst1.extend(lst2)

In [154]:
lst1

[1, 2, 3, 4]

In [155]:
lst1 = [1, 2]
lst2 = [3, 4]
t1 = np.array(lst1)
t2 = np.array(lst2)

In [160]:
np.sqrt(np.sum( (t1 - t2)**2 ))

2.8284271247461903

In [165]:
t = np.array([[0, 0], [2, 1]])

In [171]:
p = np.array([1.1, 4])

In [172]:
nearest(t, p)

1

# mes idées
- fonction de génération des points du nuage
- fonction d'affichage des points
- fonction de calcul du barycentre d'un nuage de points
- structures de données : tab des barycentres, tableau des classes

In [229]:
def dist(p1, p2):
#    return np.sqrt(np.sum( (p1 - p2)**2 ))

def nearest(tab, p):
    d = float("inf")
    i = 0
    for j in range(len(tab)):
        d_j = dist(tab[j], p)
        if d_j < d:
            d = d_j
            i = j
    return i

# fonction d'affichage des points
def disp(tab):
    '''
    entrée : tableau tab = [ [x_0, y_0], [x_1, y_1], ... ]
    sortie : affichage des points associés aux couples
    '''
    n_points = len(tab)
    t_x = tab[:,0]
    t_y = tab[:,1]
    plt.plot(t_x, t_y, "o")

# calcul du barycentre d'un nuage de points
def center(tab):
    n = len(tab)
    x_c = 0.0
    y_c = 0.0
    for i in range(n):
        x_c += tab[i][0]
        y_c += tab[i][1]
    return np.array([x_c, y_c]) / n

def center(tab):
    return sum(tab) / len(tab)

def shuffle(tab):
    n = len(tab)
    for i in range(1, n):
        j = rd.randint(0,i)
        tab[i], tab[j] = tab[j], tab[i]

def mu_init(tab_points, k):
    n_points = len(tab_points)
    tab_idx = [i for i in range(n_points)]
    shuffle(tab_idx)
    tab_mu = [tab_points[tab_idx[i]] for i in range(k)]
    return np.array(tab_mu)

def make_class(tab_points, tab_mu):
    n_points = len(tab_points)
    k = len(tab_mu)
    tab_class = np.zeros(n_points, dtype=int)
    for i in range(n_points):
        tab_class[i] = nearest(tab_mu, tab_points[i])
    return tab_class


# nombre de points
n_points = 8
tab_points = rd.rand(n_points, 2)
#print(tab_points)

# nombre de classes choisi
k = 3
tab_mu = mu_init(tab_points, k)
tab_class = make_class(tab_points, tab_mu)
#print(tab_mu)
print(tab_class)

In [231]:
# nombre de points
n_points = 8
tab_points = rd.rand(n_points, 2)
#print(tab_points)

# nombre de classes choisi
k = 3
tab_mu = mu_init(tab_points, k)
tab_class = make_class(tab_points, tab_mu)
#print(tab_mu)
print(tab_class)

[1 1 2 0 2 2 2 2]


In [202]:

t = rd.rand(8,2)

array([0.44101176, 0.67089259])

In [188]:
t = rd.rand(8,2)

In [203]:
print(t)

[[0.66873191 0.7388889 ]
 [0.56388698 0.91021674]
 [0.07513143 0.9483904 ]
 [0.35533273 0.16444072]
 [0.72068818 0.74597683]
 [0.17628513 0.77426883]
 [0.72051977 0.52972023]
 [0.24751795 0.55523811]]


In [205]:
sum(t) / len(tab)

array([0.44101176, 0.67089259])